import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Insomniac - Tech",
  description: "Generated by Insomniac",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#0F0F0F] flex items-center min-h-screen flex-col">
        <div className="w-screen md:w-220 min-h-screen flex flex-col items-center">
          <Header/>
          <main className="grow">{children}</main>
          <Footer/>
        </div>

      </body>
    </html>
  );
}
